{
  "formatVersion": "1.1",
  "component": {
    "group": "jiagu",
    "module": "jiagu-plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jiagu-plugin-1.0.jar",
          "url": "jiagu-plugin-1.0.jar",
          "size": 10663,
          "sha512": "35097d7ccf70b7e593c8ce4ecbbe45a043fc9b9273803b55a12304ee3cd41e39fecd0c9d2f2fccc7cb498320db49191dcc4af357fb73660a96f1ab48f8111530",
          "sha256": "0ed54f33bf7e5825d97935bb4ad37f599e7afa25e215810775bdafe0c8f9fc1a",
          "sha1": "0db788a38017d7b9a8a6eb55b6e176fb8e9b929e",
          "md5": "d1fe11b063cb2e8beb50779428677645"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "jiagu-plugin-1.0.jar",
          "url": "jiagu-plugin-1.0.jar",
          "size": 10663,
          "sha512": "35097d7ccf70b7e593c8ce4ecbbe45a043fc9b9273803b55a12304ee3cd41e39fecd0c9d2f2fccc7cb498320db49191dcc4af357fb73660a96f1ab48f8111530",
          "sha256": "0ed54f33bf7e5825d97935bb4ad37f599e7afa25e215810775bdafe0c8f9fc1a",
          "sha1": "0db788a38017d7b9a8a6eb55b6e176fb8e9b929e",
          "md5": "d1fe11b063cb2e8beb50779428677645"
        }
      ]
    }
  ]
}
